# Type stubs for the parts of pyrage (age encryption, PyPI `pyrage`) the app uses.
# pyrage ships no stubs of its own; these follow its runtime signatures (1.4.0).
from pyrage import x25519 as x25519

class EncryptError(Exception): ...
class DecryptError(Exception): ...
class IdentityError(Exception): ...
class RecipientError(Exception): ...

def encrypt(
    plaintext: bytes, recipients: list[x25519.Recipient], armored: bool = False
) -> bytes: ...
def decrypt(ciphertext: bytes, identities: list[x25519.Identity]) -> bytes: ...
